### ISSUE TITLE
Have you compared it with the official TF implementation?

### ISSUE THREAD

**Issue by Vermeille** [mseitzer/pytorch-fid#11]
Hi,
Have you compared it with the official TF implementation? Are the score significantly different? Are there pitfalls one should be about when using it that might get significantly different results than TF?

Thanks, and thank you for writing that code.

**Comment by mseitzer** [comment]
Hi,
I am actually in the process of comparing it with TF's implementation, and I will update with more info once I get around to do so.

Unfortunately, so far I have got pretty different results between this and TF's version. At the moment, I would not recommend using the results from this implementation for anything serious. I am currently digging into where the differences stem from.

**Comment by Vermeille** [comment]
Thank you for your answer :)

**Comment by Noobcodeer** [comment]
Could you tell me how to use the fid of tensorflow? Thank you very much！

**Comment by mseitzer** [comment]
Hey,
after some long detective work I found several sources of errors between the TF and Pytorch implementation. It turns out that the Inception model of Pytorch uses different weights and a slightly different model than Tensorflow's Inception. This introduced a significant source of error. I pushed an updated version of the model (see #16), which fixes those errors. 

The model itself now computes the same results as the TF model when inputting the exact same image. There might be other sources of error (e.g. image interpolation) which could result in the FID score still being slightly different. However, I think the results should now be pretty comparable.

**Comment by Vermeille** [comment]
Thank you SO MUCH.

You're making my life so much easier with that!

Kudos to you for your excellent work!

**Comment by mseitzer** [comment]
You're welcome. Out of interest, what you are doing that is so much easier with Pytorch than Tensorflow?

**Comment by Vermeille** [comment]
You're preventing me from installing TF, which messes with my CUDA version on some of my systems and doesn't play nicely with pytorch.

You're basically making my life easier and preventing me some sysadmin pain.

**Comment by mseitzer** [comment]
I see. Yeah, CUDA and Tensorflow is a mess.
