### ISSUE TITLE
Using Imagenet Pretrained Model for CIFAR10/100

### ISSUE THREAD

**Issue by nbansal90** [mseitzer/pytorch-fid#2]
Hi!

Thanks Indeed for the code! It was really easy to follow.
I was working on Similar areas, where I need to check the quality of the Image Generated by the GANs for a CIFAR10/100 dataset.

I had a small query though. When I load the Inception model, I find the pretrained model is based on an Imagenet Dataset. Now supposing that I am doing a task based on CIFAR10 Dataset on GAN. How can I use the model for Imagenet since CIFAR10 has a size of 32x32 and number of classes is 10, where as in Imagenet it is about 224x224 and classes are 1000.

Do I need to change anything while calculating IS and FID for dataset such as CIFAR10/100 or CelebA?
Any comments or suggestion would be really appreciated!

Regards,
Nitin Bansal

**Comment by mseitzer** [comment]
Hi,

you do not have change anything to calculate the FID score for a GAN trained on CIFAR10/100. Images are automatically resized to the image size expected by the Inception model. 

One nice thing about FID and IS is that they are dataset independent (because they are based on an Inception model trained on ImageNet). Otherwise you would have to retrain a network for each dataset you want to evaluate, which is inconvenient and also makes it more difficult to compare scores from different people.
